services:
  usersdb:
    image: mysql
    container_name: mysql-ms
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ROOT_PASSWORD: minhhieu2503
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - host
  users:
    image: "hosting-demo:v1"
    container_name: hosting-ms
    ports:
      - "8080:8080"
    depends_on:
      usersdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "hosting-demo"
      SPRING_DATASOURCE_URL: "jdbc:mysql://usersdb:3306/usersdb"
    networks:
      - host

networks:
  host:
    driver: "bridge"
