server:
  port: 8080
spring:
  application:
    name: "hosting-demo"
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: minhhieu2503
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
